routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('config:clear');
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('config:cache');
    $exitCode = Artisan::call('view:cache');
    return 'DONE'; //Return anything
});
Route::get('localization/{locale}','LocalizationController@lang');

Route::get('/', 'WelcomeController@index')->name('welcome.page');
Route::post('/compare-page', 'WelcomeController@comparepage');

Route::post('/price/filter','WelcomeController@filterprice')->name('price.filter');

// Route::get('/layouts3', 'WelcomeController@layout')->name('layouts.new');
// show View all , Special , New , Popular , Top Selling Prodcts

Route::get('offers','WelcomeController@offers');
Route::get('/new/product','WelcomeController@newproduct')->name('new.product');
Route::get('/popular/product','WelcomeController@popularproduct')->name('popular.product');
Route::get('/top/product','WelcomeController@topProduct')->name('topsell.product');
Route::get('/category/{name}/','WelcomeController@Categorylist')->name('category.list');
Route::get('/Subcategory/list/{id}','WelcomeController@SubCategorylist')->name('subcategory.list');


Route::get('/products/list/{id}','WelcomeController@productslist')->name('products.list');

Route::post('sendproductemail','WelcomeController@sendproductemail');

Route::post('subscribe','WelcomeController@subscribe');


Auth::routes();

    Route::get('/checkout-form' , 'HomeController@checkoutForm')->name('checkout.form');
    Route::post('/checout-form/post' , 'HomeController@Checkoutpost')->name('checkout-form.post');
    Route::get('/transaction' ,'HomeController@transaction')->name('transaction');

    Route::post('/cart/add/{id}','HomeController@cartadd')->name('cart.added');

    Route::get('/wishlist/add/{id}','HomeController@wishlist')->name('wishlist.add');

    // Route::get('/wishlist/update/{id}','HomeController@wishlistUpdate')->name('wishlist.update');

    
    Route::get('/checkout/cart','HomeController@checkoutcart')->name('checkout.cart');
    Route::get('/home', 'HomeController@index')->name('home');
  

    Route::get('/customer/dashboard', 'HomeController@CustomerDashboard')->name('customer.dashboard');

// admin Middleware Section
    Route::get('/admin/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/admin/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    
    Route::prefix('admin')->middleware('auth:admin')->group(function() {
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/logout','Auth\AdminLoginController@logout')->name('admin.logout');

    Route::get('/main-categories' , 'CategoriesController@mainCategory')->name('main-categories');
    Route::get('/main-categories/form' , 'CategoriesController@mainCategoryForm')->name('main-categories.form');
    Route::post('/main-categories/create' , 'CategoriesController@mainCategoryCreate')->name('main-categories.create');



    //  Product dropdown route
    Route::get('/categories','CategoriesController@index');
    Route::get('/categories/form','CategoriesController@create');
    Route::post('/categories/form','CategoriesController@store')->name('add.categories');
    Route::get('/categories/form/{id}','CategoriesController@edit')->name('edit.categories');
    Route::post('/categories/form/{id}','CategoriesController@update')->name('update.categories');
    Route::get('/categories/delete{id}','CategoriesController@delete')->name('delete.categories');
    Route::get('/categories/trash','CategoriesController@categoriesTrash')->name('trash.categories');

    Route::get('/subcategories','CategoriesController@subcategories');
    Route::get('/subcategories/form','CategoriesController@subcategoriesform');
    Route::post('/subcategories/form','CategoriesController@subcategoriesformpost');

    Route::get('/subcategories/edit/{id}','CategoriesController@subcategoriesformedit');
    Route::post('/subcategories/formeditpost','CategoriesController@subcategoriesformeditpost');

    Route::post('/getcategories', 'CategoriesController@getcategories');
    Route::post('/getsubcategories', 'CategoriesController@getsubcategories');

    // subcategories delet
    Route::get('/subcategories/delete/{id}','CategoriesController@subcategories_delet')->name('subcategories.delete');
    Route::get('/subcategories/trash','CategoriesController@trashsubcategories')->name('trash.subcategories');


//    Route::get('/banners','ContentContrroller@index');

    Route::get('/brands','CategoriesController@brands');
    Route::get('/barnds/add','CategoriesController@addbrands')->name('add.brands');
    Route::post('/barnds/store','CategoriesController@storebrands')->name('brands.create');
    Route::get('/brands/edit/{id}','CategoriesController@editbrand')->name('brands.edit');
    Route::post('/brands/update/{id}','CategoriesController@updatebrand')->name('brnads.update');
    Route::get('/brands/delete/{id}','CategoriesController@deletebrand')->name('brnads.delete');
    Route::get('/brands/trash','CategoriesController@trashbrand')->name('brands.trash');

    Route::get('/products','CategoriesController@products');
    Route::get('/products/add','CategoriesController@addproducts')->name('add.products');
    Route::post('/products/addformpost','CategoriesController@addproductspost');
    Route::get('/products/edit/{id}','CategoriesController@editproduct');
    Route::post('/products/editpost/{id}','CategoriesController@editproductpost');
    Route::post('/products/delete/{id}','CategoriesController@productdelete')->name('product.delete');
    Route::get('/products/trash','CategoriesController@producttrash')->name('trash.products');


    Route::post('/products/deleteproductattribute','CategoriesController@deleteproductattribute');


    Route::post('/products/filter/categories','CategoriesController@Filterbycategoru')->name('categories.filter');

    Route::get('/pages','CategoriesController@information');
    Route::get('/pages/add','CategoriesController@pagesadd');
    Route::post('/pages/addpost','CategoriesController@pagesaddpost');

    Route::get('/pages/addlink','CategoriesController@pagesaddlink');
    Route::post('/pages/addlinkpost','CategoriesController@pagesaddlinkpost');

    // Promotion Dropdown route
    
    Route::get('/product_offers', 'PromotionController@product_offers');
    Route::get('/product_offers/form','PromotionController@add_product_wise_offer')->name('products.offers');
    Route::get('/product_offers/edit/{id}', 'PromotionController@product_offersedit');
    Route::post('/product_offers/formpostedit','PromotionController@product_formpostedit');
    Route::get('/product_offers/delete/{id}','PromotionController@product_offers_delete')->name('product_offer.delete');
    Route::post('/product_offers/formpost','PromotionController@product_offerspost');

    Route::post('/getsubcategoryproducts','PromotionController@getsubcategoryproducts');
    Route::post('/getsubcategoryproducts1','PromotionController@getsubcategoryproducts1');

    Route::post('/productpromotionremoveproduct','PromotionController@productpromotionremoveproduct');


  
    // categories offer
    Route::get('/category_offers','PromotionController@category_wise_offers');
    Route::get('/category_wise_offers/form','PromotionController@category_wise_offersform');
    Route::post('/category_wise_offers/formpost','PromotionController@category_wise_offersformpost');
    Route::get('/category_offers/edit/{id}', 'PromotionController@category_offersedit');
    Route::post('/category_wise_offers/formpostedit', 'PromotionController@category_offerseditpost');


    // subcategories offer
    Route::get('/sub_category_wise_offers/form','PromotionController@sub_category_wise_offers');
    Route::post('/sub_category_wise_offers/formpost','PromotionController@sub_category_wise_offersformpost');
    Route::get('/sub_category_offers', 'PromotionController@sub_category_offers');
    Route::get('/sub_category_offers/edit/{id}', 'PromotionController@sub_category_offersedit');
    Route::post('/sub_category_wise_offers/formpostedit', 'PromotionController@sub_category_offerseditpost');
    Route::get('/sub_category_wise_offers/delete/{id}','PromotionController@sub_categorire_offers_delete')->name('sub_categories_offer.delete');


    // brands offers
    Route::get('/brand_offers', 'PromotionController@brandoffers');
    Route::get('/brand_offers/edit/{id}', 'PromotionController@brandoffersedit');
    Route::post('/brand_offers/formpostedit', 'PromotionController@brandofferseditpost');
    Route::get('/brand_offers/form','PromotionController@brandoffersform');
    Route::post('/brand_offers/formpost','PromotionController@brandoffersformpost');
     Route::get('/brand_offers/delete/{id}','PromotionController@brandoffers_delete')->name('brands_offers_delete');
    
    
    // sales dropdown route

    Route::get('/orders', 'SalesController@index');
    Route::get('/orders/items/{id}', 'SalesController@show')->name('orderitem.show');
    Route::post('/orders/update/{id}', 'SalesController@update')->name('order.update');

    Route::get('/orders/confirmbyAdmin', 'SalesController@confirmbyAdmin');
    Route::get('/orders/confirmbyajent', 'SalesController@confirmbyajent');

  

    // content dropdown route
    Route::get('/banners', 'ContentController@index');
    Route::get('/banners/add', 'ContentController@create');
    Route::post('/banners/addpost', 'ContentController@createpost');

app/Cart.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cart extends Model
{
    //
    protected $table = 'cart';

    public function getTotalAttribute()
    {
        return $this->product->price * $this->productquantity;
    }
    
    public function getTotalFormattedAttribute()
    {
        return number_format($this->total, 2);
    }


    public function product()
    {
        return $this->belongsTo(products::class, 'productid');
    }
}

resources/views/front-end/checkout-form.blade.php
@extends('layouts.front-app')
@section('content')
<div class="container">
	@php
	$cartCount = 0; 
	$cartCount = \App\Cart::where(['user_id' => auth()->id(), 'status' => 0])->count();
	@endphp

	@if($cartCount != 0)
    <div class="py-5 text-center">
        <h2>Checkout</h2>
        <p class="lead">Need Some Informtion"</p>
    </div>
    <div class="stepwizard col-md-offset-3">
    	<div class="stepwizard-row setup-panel">
      		<div class="stepwizard-step">
        		<a href="#step-1" type="button" class="btn in-active-step btn-circle">1</a>
        		<p>Account</p>
      		</div>
      		<div class="stepwizard-step">
        		<a href="#step-2" type="button" class="btn btn-default btn-circle btn-primary" disabled="disabled">2</a>
        		<p>Address</p>
      		</div>
      		<div class="stepwizard-step">
        		<a href="#step-3" type="button" class="btn btn-default btn-circle in-active-step" disabled="disabled">3</a>
        		<p>Payment</p>
      		</div>
    	</div>
  	</div>
    <div class="row">
        <div class="col-md-4 order-md-2 mt-4 mb-4 border-gray p-0">
            <div class="payment">
            	<h4 class="mt-3 ml-4">Cart - item(s)</h4>
            </div>	
			
			
			@foreach ($cartItems as $item)
				@php $product = $item->product; @endphp
				<div class="col-md-12 mt-4 mb-4 border-bottom-img">
					<div class="row product-container">
						<div class="col-md-4 col-sm-4 col-xs-4">
							<div class="product-img">
								@foreach (json_decode($product->image) as $key => $products)

									@if($key == 0)
										<img height="100" width="100" src="{{asset('public/images/products/'.$products)}}" class="img-thumbnail rounded" >
									@endif
								@endforeach
							</div>
						</div>
						<div class="col-md-8 col-sm-8 col-xs-8">
						<p class="product-text">{{$product->prod_name}}</p>
							<p>{{$item->productquantity}} x  {{$item->total_formatted}}</p>
						</div>
					</div>	
				</div>
			@endforeach

    	
    		<div class="payment">
            	<h4 class="mt-3 ml-4">Total</h4>
            </div>

    		<div class="col-md-12 mt-4 mb-4 border-bottom-img">
    			<div class="row product-container">
	        		<div class="col-md-12 col-sm-12 col-xs-12">
	            		<table class="table">
							@php 
							$total = $cartItems->sum('total');
							$vatotal = App\Vat::where('vatselect',1)->first();
							$vat = $total * $vatotal->vatpercentage / 100; 
							@endphp
                			<tbody>
                				<tr>
                					<td> Subtotal:</td>
                					<td class="text-right">SR {{number_format($total, 2)}}</td>
								</tr>
								<tr>
									<td>
										<strong>VAt 15%:</strong>
									</td>
									<td class="text-right">
										<strong>SR {{number_format($vat, 2)}}</strong>
									</td>
								</tr>
  								<tr>
  									<td>
  										<strong>Total:</strong>
  									</td>
  									<td class="text-right">
  										<strong>SR {{ number_format($total + $vat, 2) }}</strong>
  									</td>
								</tr>
                			</tbody>
            			</table>
	        		</div>
	        	</div>	
    		</div>
        </div>

        <div class="col-md-8 order-md-1 mt-4 mb-4">
        	<div class="payment">
            	<h4 class="mt-3 ml-4">Payment & Shipping Address</h4>
            </div>	
                <div class="row mt-3">
                    <div class="col-md-6 mb-3">
                        <label for="firstName">First name</label>
					<input type="text" class="form-control" id="firstName" value="{{$customerinfo->name}}" placeholder="First name" readonly>
                        
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="lastName">Last name</label>
                        <input type="text" class="form-control" id="lastName" value="{{$customerinfo->lastname}}" placeholder="Last name" readonly>
                        
                    </div>
                </div>
                <div class="mb-3">
                    <label for="email">Email <span class="text-muted">(Optional)</span></label>
                    <input type="email" class="form-control" value="{{$customerinfo->email}}" id="email" placeholder="Email" readonly>
                </div>
                <div class="mb-3">
                    <label for="mobile-number">Mobile Number</label>
                    <input type="tel" class="form-control" value="{{$customerinfo->phone}}" id="mobile-number" placeholder="Mobile number" readonly>
                    
                </div>	
				<div class="mb-3">
                    <label for="country">Country</label>
                    <input type="text" class="form-control" id="country" value="{{$customerinfo->country}}" readonly>
                    
				</div>
				<div class="mb-3">
                    <label for="city">City</label>
                    <input type="text" class="form-control" id="city" value="{{$customerinfo->city}}" readonly>
                    
                </div>

                <div class="mb-3">
                    <label for="address">Address</label>
                    <input type="text" class="form-control" id="address" value="{{$customerinfo->address}}" readonly>
                    
                </div>
                <div class="custom-control custom-checkbox mb-3">
                    <input type="checkbox" class="custom-control-input" id="ship-to-another">
                    <label class="custom-control-label" for="ship-to-another">Shipping to another address</label>
				</div>

				<form action="{{route('checkout-form.post')}}" method="POST" >
					@csrf

					<input type="hidden" name="total" value="{{number_format($total, 2)}}">
					<input type="hidden" name="vat" value="{{number_format($vat, 2)}}">
					<input type="hidden" name="subtotal" value="{{ number_format($total + $vat, 2) }}">

					<div id="changeShipInputs">
						<div class="mb-3">
							<label for="person-name">Name</label>
							<input type="text" class="form-control" name="shipping_name" id="person-name" placeholder="Name" >
						
						</div>

						<div class="mb-3">
							<label for="person-mob-no">Mobile Number</label>
							<input type="tel" class="form-control" id="person-mob-no" name="shipping_phone" placeholder="Mobile Number" >
						
						</div>

						<div class="mb-3">
							<label for="person-mob-no">Address</label>
							<input type="text" class="form-control" id="another-ship-address" name="shipping_address" placeholder="Another ship address" > 
						</div> 
					</div>    
					<button class="btn btn-primary btn-lg btn-block" type="submit">Save Address</button>
				</form>
        </div>
    </div>
    @else
        
		<div class="text-center">
			<p>There are no items in this cart</p>
			<a href="{{ url('/') }}" type="button" class=" btn btn-success">Continue Shoping</a>
		</div>
	@endif
</div>
@endsection

resources/views/front-end/checkout.blade.php
@extends('layouts.front-app')
@section('content')

{{-- @php 
$cartCount = 0;
if (auth()->check()) {
    $cartCount = \App\Cart::where(['user_id' => auth()->id(), 'status' => 0])->get();
    $productclist = 
}
@endphp --}}

<div class="container py-5 text-center">
	<h2>Cart</h2>
	<p class="lead">Need Some Informtion"</p>
</div>
<div class="px-4 px-lg-0">
	<div class="pb-5">
        @php 
        $cartCount = 0; 
        $cartCount = \App\Cart::where(['user_id' => auth()->id(), 'status' => 0])->count();
        @endphp
        
        @if($cartCount != 0)
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12 pl-5 pr-5 bg-white rounded">
					<div class="table-responsive">
						<table class="table cart-table" cellspacing="0">
							<thead>
								<tr>
									<th class="product-remove">&nbsp;</th>
									<th class="product-thumbnail">Image</th>
									<th class="product-name">Product</th>
									<th class="product-price">Price</th>
									<th class="product-quantity">Quantity</th>
									<th class="product-subtotal">Total</th>
								</tr>
							</thead>
							<tbody>
                               
                                @foreach ($cartItems as $item)
										@php $product = $item->product; @endphp
									
										
											<tr>
												<td class="product-remove">
													<a href="#" class="remove">
														<i class="fa fa-times"></i>
													</a>						
												</td>

												<td class="product-thumbnail">
													@foreach (json_decode($product->image) as $key => $products)

														@if($key == 0)

															<a href="#">
															<img width="100" width="100" src="{{asset('public/images/products/'.$products)}}" class="img-fluid rounded shadow-sm" alt="" >
															</a>
														@endif
													@endforeach
												
												</td>

												<td class="product-name">
												<a href="#">{{$product->prod_name}}</a>
												</td>

												<td class="product-price">
													<span class="amount">
														<bdi>
															<span class="currencySymbol">SR</span> {{$product->price}}
														</bdi>
													</span>
												</td>

												<td class="product-quantity" style="text-align: -webkit-center;">
													<div class="number-input md-number-input">
														<button onclick="this.parentNode.querySelector('input[type=number]').stepDown()" class="minus"></button>
														<input class="quantity" min="0" name="quantity" value="{{$item->productquantity}}" type="number">
														<button onclick="this.parentNode.querySelector('input[type=number]').stepUp()" class="plus"></button>
														
														
													</div>
													
												</td>

												<td class="product-subtotal">
													<span class="price-amount amount">
														<bdi>
															<span class="currencySymbol">SR</span> {{$item->total_formatted}}
														</bdi>
													</span>						
												</td>
											</tr>
								@endforeach
								
							</tbody>
						</table>
					</div>
				</div>
			</div>

			{{--<div class="row bg-white">
				<div class="col-lg-6">
                        
                    <div class="actions">
                        <div class="coupon">
                            <div class="input-group mb-4 border rounded p-2">
                            <input type="text" placeholder="Apply coupon" aria-describedby="button-addon3" class="form-control border-0">
                                <div class="input-group-append border-0">
                                    <button id="button-addon3" type="button" class="btn btn-dark px-4 rounded btn-primary">
                                        <i class="fa fa-gift mr-2"></i>Apply coupon</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                 <div class="col-lg-6">
                    <div class="actions text-center">
                        <div class="input-group mb-4 rounded-pill">
                            <div class="input-group-append border-0">
                                <button id="button-addon3" type="button" class="btn btn-dark px-4 rounded-pill btn-primary">
                                    Update</button>
                            </div>
                        </div>
                        
                    </div>
                </div> 

				
			</div>--}}
p
			@php 
				$total = $cartItems->sum('total');
				$vatotal = App\Vat::where('vatselect',1)->first();
                $vat = $total * $vatotal->vatpercentage / 100; 
			@endphp
			<div class="row bg-white">
                <div class="col-lg-6">
					<a href="{{ url('/') }}" type="button" style="    margin-top: 300px;" class="btn btn-dark  btn-primary">Continue Shoping</a>
				</div>
                <div class="col-lg-6 rounded-pill">
					<div class="px-4 py-3 text-uppercase font-weight-bold" style="font-size:30px;">Cart totals
					</div>
				  	<div class="p-4" style="border: 1px solid;">
					    <ul class="list-unstyled mb-4">
					    	<li class="d-flex justify-content-between py-3 border-bottom">
								<strong class="text-muted">Order Subtotal </strong>
								
							<strong>SR {{number_format($total, 2)}}</strong>
					    	</li>
					      	{{-- <li class="d-flex justify-content-between py-3 border-bottom">
					      		<strong class="text-muted">Shipping and handling</strong>
					      		<strong>$10.00</strong></li> --}}
					      	<li class="d-flex justify-content-between py-3 border-bottom">
								<strong class="text-muted">VAT 15%</strong>
					      		<strong>SR {{number_format($vat, 2)}}</strong>
					      	</li>
					      	<li class="d-flex justify-content-between py-3 border-bottom">
								  <strong class="text-muted">Total</strong>
								
							  <h5 class="font-weight-bold"> {{ number_format($total + $vat, 2) }}</h5>
					      	</li>
					    </ul>
				    	<a href="{{route('checkout.form')}}" class="btn btn-dark rounded py-2 btn-block btn-primary">Procceed to checkout</a>
				  </div>
				</div>
            </div>
	
        </div>
        @else
        
        <div class="text-center">
			<p>There are no items in this cart</p>
        	<a href="{{ url('/') }}" type="button" class="btn btn-dark  btn-primary">Continue Shoping</a>
        </div>
        @endif
       
  	</div>
</div>




@endsection

resources/views/front-end/customer_dashboard.blade.php
@extends('layouts.front-app')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-12">
			<div class="page-header">
				<h1 class="mt-3 mb-3">Dashboard</h1>
			</div>
		</div>	
	</div>
</div>		
<div class="container">
	<div class="row">
		<div class="col-lg-3 col-md-3 col-sm-6">
	    	<div class="tile tile-primary">
	            <div class="tile-heading">My Orders
				</div>
				@php
				$ordersCount = 0; 
				$ordersCount = \App\Orders::where(['user_id' => auth()->id()])->count();

				$wishlistCount = 0; 
				$wishlistCount = \App\Wishlist::where(['user_id' => auth()->id()])->count();
				@endphp
	            <div class="tile-body">
	                <i class="fa fa-get-pocket"></i>                    
	                <h2 class="pull-right">{{$ordersCount}}</h2>
	            </div>
	            <div class="tile-footer">
	                <a href="#">View more...</a>
	            </div>
	    	</div>
		</div>
		<div class="col-lg-3 col-md-3 col-sm-6">
	    	<div class="tile tile-primary">
	        	<div class="tile-heading">Wish list
	        	</div>
	            <div class="tile-body">
	                <i class="fa fa-heart-o"></i>
	                 <h2 class="pull-right">{{$wishlistCount}}</h2>
	            </div>
	            <div class="tile-footer">
	                <a href="#">View more...</a>
	            </div>
	    	</div>
		</div>
		<div class="col-lg-3 col-md-3 col-sm-6">
	    	<div class="tile tile-primary">
	        	<div class="tile-heading">Share
	        	</div>
	            <div class="tile-body">
	                <i class="fa fa-share-alt"></i>
	                <h2 class="pull-right">84</h2>
	            </div>
	            <div class="tile-footer">
	                <a href="#">View more...</a>
	            </div>
	    	</div>
		</div>
		<div class="col-lg-3 col-md-3 col-sm-6">
	    	<div class="tile tile-primary">
	        	<div class="tile-heading">Profile
	        	</div>
	            <div class="tile-body">
	                <i class="fa fa-user"></i>
	                <h2 class="pull-right">Muhammad</h2>
	            </div>
	            <div class="tile-footer">
	                <a href="#">View more...</a>
	            </div>
	    	</div>
		</div>
	</div>
</div>	

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h2 class="mt-3 mb-3">My Orders</h2>
			<table class="table table-striped">
			<thead>
				<tr>
				
					<th>Date</th>
					<th>Vat</th>
					<th>Total</th>
					<th>Shipping Price</th>
					<th>Subtotal</th>
					<th>Status</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				
				
                @foreach ($orderitem as $ordershow)
                    <tr class="text-center">
						
						<td>{{$ordershow->created_at}}</td> 
						<td>{{$ordershow->vat}}</td>
						<td>{{$ordershow->total}}</td>
						<td>{{$ordershow->shipping_price == '' ? 0 : $ordershow->shipping_price}}</td> 
						<td>{{$ordershow->subtotal}}</td> 
						<td>{{$ordershow->status}}</td>
						<td class="text-right">
							<div class="btn-group">
								<a class="btn btn-default" href="#">
									<i class="fa fa-eye"></i>
								</a>
							</div>
						</td>
					</tr>
					
                @endforeach
			  
				
				</tbody>
			</table>
		</div>	
	</div>	
</div>
<div class="container">
	<div class="row">
		<div class="col-md-12" style="text-align:center;">
	    	<a class="btn btn-primary mt-3 mb-3" href="#">View All Sale</a>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<h2 class="mt-3 mb-3">Wish List</h2>
		<table class="table table-striped">
			<thead>
				<tr>
					<th class="gc_cell_right">Product Image</th>
					<th class="gc_cell_right">Product name</th>
					<th class="gc_cell_right">Product Arbic name</th>
					<th class="gc_cell_right">Product Price</th>
					<th class="gc_cell_right">Action</th>
		           
		  		</tr>
			</thead>
			<tbody>
				@foreach ($wishlist as $wishlistitem)
					@php $product = $wishlistitem->products; @endphp
				<tr class="text-center">
					@foreach (json_decode($product->image) as $key => $itemimg)

					@if($key == 0)
						<td >
							<img src="{{asset('public/images/products/'.$itemimg)}}" height="50" width="50" alt="">
						</td>
					@endif
						
					@endforeach
					

					<td >{{$product->prod_name}}</td>
					<td >{{$product->arabic_name}}</td>
					<td >{{$product->price}}</td>
					<td >
						<div class="btn-group">
						<a class="btn btn-default" href="{{route('products.list',$product->id)}}">
								<i class="fa fa-eye"></i>
							</a>
						</div>
					</td>
		    	</tr>
				@endforeach
		       
		     
		    </tbody>
		</table>
	</div>
</div>
<div class="row">
    <div class="col-md-12" style="text-align:center;">
        <a class="btn btn-primary mt-3 mb-3" href="#">View All Wish List</a>
    </div>
</div>

<div class="container">
	<div class="row">
		<h2 class="mt-3 mb-3">Share</h2>
		<table class="table table-striped">
			<thead>
				<tr>
		            <th class="gc_cell_left">First Name</th>
		            <th>Last Name</th>
		            <th>Email</th>
		            <th class="gc_cell_right">Active </th>
		  		</tr>
			</thead>
			<tbody>
		        <tr class="text-center">
		        	<td class="gc_cell_left">Muhammad</td>
		        	<td>Abdullah</td>
		            <td>
		                <a href="mailto:sdfsdf@mali.com">Muhammadabdullah@mali.com</a>
		            </td>
		        	<td>Yes</td>
		    	</tr>
		       
		    </tbody>
		</table>
	</div>
</div>
<div class="row">
    <div class="col-md-12" style="text-align:center;">
        <a class="btn btn-primary mt-3 mb-3" href="#">View All Share</a>
    </div>
</div>    
    
@endsection